//USER
export const LOADING_USER = "LOADING_USER";
export const SIGN_UP_OR_LOGIN_SUCCESS =  "SIGN_UP_OR_LOGIN_SUCCESS";
export const SIGN_UP_OR_LOGIN_FAILURE = "SIGN_UP_OR_LOGIN_FAILURE";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const EDIT_USER = "EDIT_USER";
export const ADD_USER_PHOTO = "ADD_USER_PHOTO";
export const SIGN_OUT = "SIGN_OUT";

//FARMER
export const LOADING_FARMER = "LOADING_FARMER";
export const FETCH_FARMER = "FETCH_FARMER";
export const ADD_FARMER_ERR_MESSAGE = "ADD_FARMER_ERR_MESSAGE";
export const CLEAR_FARMER = "CLEAR_FARMER";

//PROSPECT
export const LOADING_PROSPECTS = "LOADING_PROSPECTS";
export const FETCH_PROSPECTS = "FETCH_PROSPECTS";
export const LOADING_PROSPECT =  "LOADING_PROSPECT";
export const FETCH_PROSPECT = "FETCH_PROSPECT";
export const CLEAR_PROSPECTS = "CLEAR_PROSPECTS";

//LISTING
export const LOADING_LISTING = "LOADING_LISTING";
export const LOADING_LISTINGS = "LOADING_LISTINGS";
export const CREATE_NEW_LISTING = "CREATE_NEW_LISTING";
export const ADD_OPEN_LISTINGS = "ADD_OPEN_LISTINGS";
export const ADD_USER_CLOSED_LISTINGS = "ADD_USER_CLOSED_LISTINGS";
export const ADD_USER_INTERESTS_LISTINGS = "ADD_USER_INTERESTS_LISTINGS";
export const ADD_USER_INTERESTS_LISTINGS_COUNT = "ADD_USER_INTERESTS_LISTINGS_COUNT";
export const ADD_LISTING = "ADD_LISTING";
export const EDIT_LISTING = "EDIT_LISTING";
export const ADD_USER_INTEREST_TO_LISTING = "ADD_USER_INTEREST_TO_LISTING";
export const REMOVE_USER_INTEREST_ON_LISTING = "REMOVE_USER_INTEREST_ON_LISTING";
export const LISTINGS_RENDERED_TRUE = "LISTINGS_RENDERED_TRUE";
export const LISTINGS_RENDERED_FALSE = "LISTINGS_RENDERED_FALSE";
export const DELETING_LISTING = "DELETING_LISTING";
export const RESET_DELETING = "RESET_DELETING";
export const CLEAR_LOADING = "CLEAR_LOADING";
export const CLEAR_LISTINGS = "CLEAR_LISTINGS";

//COMMODITY
export const LOADING_COMMODITIES = "LOADING_COMMODITIES";
export const FETCH_COMMODITIES = "FETCH_COMMODITIES";
export const CLEAR_COMMODITIES = "CLEAR_COMMODITIES";

//INTEREST
export const LOADING_LISTINGS_INTERESTS = "LOADING_LISTINGS_INTERESTS";
export const FETCH_LISTINGS_INTERESTS = "FETCH_LISTINGS_INTERESTS";
export const CLEAR_INTERESTS = "CLEAR_INTERESTS";

//CONNECTION
export const LOADING_CONNECTS = "LOADING_CONNECTS";
export const ADD_USER_CONNECTS = "ADD_USER_CONNECTS";
export const CONNECT_USERS = "CONNECT_USERS";
export const ACCEPT_CONNECT = "ACCEPT_CONNECT";
export const UNCONNECT_USERS = "UNCONNECT_USERS";
export const CLEAR_CONNECTIONS = "CLEAR_CONNECTIONS";