//USER
export const LOADING_USER = "LOADING_USER";
export const SIGN_UP_OR_LOGIN_SUCCESS =  "SIGN_UP_OR_LOGIN_SUCCESS";
export const SIGN_UP_OR_LOGIN_FAILURE = "SIGN_UP_OR_LOGIN_FAILURE";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const EDIT_USER = "EDIT_USER";
export const ADD_USER_PHOTO = "ADD_USER_PHOTO";
export const SIGN_OUT = "SIGN_OUT";

//FARMER
export const LOADING_FARMER = "LOADING_FARMER";
export const FETCH_FARMER = "FETCH_FARMER";
export const ADD_FARMER_ERR_MESSAGE = "ADD_FARMER_ERR_MESSAGE";
export const CLEAR_FARMER = "CLEAR_FARMER";


//COMMODITY
export const LOADING_COMMODITIES = "LOADING_COMMODITIES";
export const FETCH_COMMODITIES = "FETCH_COMMODITIES";
export const CLEAR_COMMODITIES = "CLEAR_COMMODITIES";

//INTEREST
export const LOADING_LISTINGS_INTERESTS = "LOADING_LISTINGS_INTERESTS";
export const FETCH_LISTINGS_INTERESTS = "FETCH_LISTINGS_INTERESTS";
export const CLEAR_INTERESTS = "CLEAR_INTERESTS";

//CONNECTION
export const LOADING_CONNECTS = "LOADING_CONNECTS";
export const ADD_USER_CONNECTS = "ADD_USER_CONNECTS";
export const CONNECT_USERS = "CONNECT_USERS";
export const ACCEPT_CONNECT = "ACCEPT_CONNECT";
export const UNCONNECT_USERS = "UNCONNECT_USERS";
export const CLEAR_CONNECTIONS = "CLEAR_CONNECTIONS";

