//USER
export const LOADING_USER = "LOADING_USER";
export const SIGN_UP_OR_LOGIN_SUCCESS =  "SIGN_UP_OR_LOGIN_SUCCESS";
export const SIGN_UP_OR_LOGIN_FAILURE = "SIGN_UP_OR_LOGIN_FAILURE";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const EDIT_USER = "EDIT_USER";
export const ADD_USER_PHOTO = "ADD_USER_PHOTO";
export const SIGN_OUT = "SIGN_OUT";

//COMMODITY
export const LOADING_COMMODITIES = "LOADING_COMMODITIES";
export const FETCH_COMMODITIES = "FETCH_COMMODITIES";
export const CLEAR_COMMODITIES = "CLEAR_COMMODITIES";
